# Generated by Django 3.2.2 on 2022-02-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_for_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Email_Id', models.EmailField(max_length=254)),
                ('phone_Number', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('Flat_no', models.IntegerField()),
                ('street', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('upload_photo', models.ImageField(upload_to='new')),
            ],
        ),
    ]
